project:
  type: website
  output-dir: docs
  preview:
    port: 2025

website:
  # title: "ICBBG 2025"
  favicon: "./img/icbbg.svg"
  navbar:
    background: primary
    logo: ./img/icbbg-logo.svg
    
    right:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - importantdates.qmd
      - committees.qmd
      - announcements.qmd
      - speakers.qmd
      - venue.qmd
      - registration.qmd 
      - publication.qmd
      - sponsors.qmd
      - about.qmd

  sidebar:
    style: "floating"
    search: true
    contents:
      - index.qmd
      - schedule.qmd
      - importantdates.qmd
      - committees.qmd
      - announcements.qmd
      - speakers.qmd
      - venue.qmd
      - registration.qmd 
      - publication.qmd
      - sponsors.qmd
      - about.qmd
format:
  html:
    theme: 
      - ./src/theme/cbbg.scss
    css:
      - ./src/theme/styles.css
    toc: true

execute:
  echo: false
  freeze: auto
  warning: false
  error: false
