project:
  type: website
  output-dir: docs

website:
  title: "I-CBBG 2024"
  navbar:
    type: dark
    background: primary
    
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - importantdates.qmd
      - committees.qmd
      - announcements.qmd
      - speakers.qmd
      - venue.qmd
      - registration.qmd 
      - publication.qmd
      - sponsors.qmd
      - about.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - schedule.qmd
      - importantdates.qmd
      - committees.qmd
      - announcements.qmd
      - speakers.qmd
      - venue.qmd
      - registration.qmd 
      - publication.qmd
      - sponsors.qmd
      - about.qmd
format:
  html:
    theme: 
      - ./src/theme/cbbg.scss
      - flatly
    toc: true



