project:
  type: website
  output-dir: _site

website:
  title: "I-CBBG 2024"
  navbar:
    background: primary
    
    right:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - importantdates.qmd
      - committees.qmd
      - announcements.qmd
      - speakers.qmd
      - venue.qmd
      - registration.qmd 
      - publication.qmd
      - sponsors.qmd
      - about.qmd

  sidebar:
    style: "floating"
    search: true
    contents:
      - index.qmd
      - schedule.qmd
      - importantdates.qmd
      - committees.qmd
      - announcements.qmd
      - speakers.qmd
      - venue.qmd
      - registration.qmd 
      - publication.qmd
      - sponsors.qmd
      - about.qmd
format:
  html:
    theme: 
      - flatly
      - ./src/theme/cbbg.scss
    toc: true



