project:
  type: website
  output-dir: docs
  preview:
    port: 2025

website:
  # title: "ICBBG 2025"
  page-footer: "Coyright 2025 @ICBBG"
  google-analytics: G-12S45SR1D0
  favicon: "./img/icbbg.svg"
  navbar:
    background: primary
    logo: ./img/icbbg-logo.svg
    
    right:
      - href: index.qmd
        text: Home
      - program.qmd
      - importantdates.qmd
      - submissions.qmd
      - speakers.qmd
      - registration.qmd 
      - sponsors.qmd
      - committees.qmd
      - venue.qmd
      - about.qmd

  sidebar:
    style: "floating"
    search: true
    contents:
      - href: ./submissions/call-for-poster.qmd
        text: Submit a poster
      - href: registration.qmd
        text: Register
  announcement:
    icon: info-circle-fill
    dismissable: true
    content: "**Update on Paper Reviews: Expecting Some Delays.** [Learn More](/review-update.qmd)"
    type: danger
    position: below-navbar
format:
  html:
    theme: 
      - ./assets/theme/cbbg.scss
    css:
      - ./assets/theme/styles.css
    toc: true
    email-obfuscation: javascript
    # include-in-header: 
    #   - assets/theme/banner.html
    filters: 
      - ./assets/theme/highlight-span.lua
execute:
  echo: false
  freeze: auto
  warning: false
  error: false
